#!/usr/bin/env bash
# Test Suite: US-004 — Self-Verification Redesign - Re-Execution Cycle
# IL-4: 3+ tests per AC (happy + negative + boundary)
# 13 ACs x 3 = 39 tests minimum

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CMD="$ROOT/src/commands/rlp-desk.md"
RUN="$ROOT/src/scripts/run_ralph_desk.zsh"
GOV="$ROOT/src/governance.md"
INIT="$ROOT/src/scripts/init_ralph_desk.zsh"

PASS=0
FAIL=0

pass() { PASS=$((PASS+1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1"; }

grep_count() {
  local n
  n=$(grep -c "$1" "$2" 2>/dev/null) || n=0
  echo "$n"
}
grep_exists() { grep -q "$1" "$2" 2>/dev/null && echo 1 || echo 0; }

assert_eq() {
  local val="$1" expected="$2" label="$3"
  if [[ "$val" -eq "$expected" ]]; then pass "$label"; else fail "$label (got $val, expected $expected)"; fi
}
assert_ge() {
  local val="$1" min="$2" label="$3"
  if [[ "$val" -ge "$min" ]]; then pass "$label"; else fail "$label (got $val, expected >=$min)"; fi
}
assert_zero() { assert_eq "$1" 0 "$2"; }

echo "=== US-004: Self-Verification Redesign - Re-Execution Cycle ==="
echo ""

# ============================================================
# AC1: --mode fresh|improve argument in init_ralph_desk.zsh
# ============================================================

# AC1-happy: --mode appears at least 3 times (definition + 2 branches/checks)
count=$(grep_count '\-\-mode' "$INIT")
assert_ge "$count" 3 "AC1-happy: --mode appears >= 3 times in init_ralph_desk.zsh"

# AC1-negative: 'fresh' value is explicitly handled in init script
count=$(grep_count 'fresh' "$INIT")
assert_ge "$count" 1 "AC1-negative: 'fresh' mode handled in init_ralph_desk.zsh"

# AC1-boundary: 'improve' value is explicitly handled in init script
count=$(grep_count 'improve' "$INIT")
assert_ge "$count" 1 "AC1-boundary: 'improve' mode handled in init_ralph_desk.zsh"

# ============================================================
# AC2: version_file() and detect_next_version() functions
# ============================================================

# AC2-happy: version_file appears >= 3 times (definition + 2 calls for debug.log + campaign-report.md)
count=$(grep_count 'version_file' "$INIT")
assert_ge "$count" 3 "AC2-happy: version_file appears >= 3 times in init_ralph_desk.zsh"

# AC2-negative: detect_next_version appears >= 2 times (definition + call inside version_file)
count=$(grep_count 'detect_next_version' "$INIT")
assert_ge "$count" 2 "AC2-negative: detect_next_version appears >= 2 times in init_ralph_desk.zsh"

# AC2-boundary: -v{N} suffix pattern used for versioned files (not -NNN which is SV reports)
count=$(grep_count '\-v\${' "$INIT")
assert_ge "$count" 1 "AC2-boundary: -v\${N} suffix pattern present in init_ralph_desk.zsh"

# ============================================================
# AC3: Re-execution delete/reset for --mode improve
# ============================================================

# AC3-happy: iter-* artifact deletion logic present
count=$(grep_count 'iter-\*\|iter-.*artifact\|delete.*iter' "$INIT")
assert_ge "$count" 1 "AC3-happy: iter-* artifact deletion logic in init_ralph_desk.zsh"

# AC3-negative: status.json, cost-log.jsonl, baseline.log in deletion list
count=$(grep_count 'status\.json\|cost-log\.jsonl\|baseline\.log' "$INIT")
assert_ge "$count" 1 "AC3-negative: status.json/cost-log.jsonl/baseline.log deletion in init_ralph_desk.zsh"

# AC3-boundary: memory and context files reset via rm (will be regenerated by scaffold below)
count=$(grep_count 'rm.*memory\|rm.*context' "$INIT")
assert_ge "$count" 1 "AC3-boundary: memory/context reset (rm then regenerate) in init_ralph_desk.zsh"

# ============================================================
# AC4: PRD handling by mode — fresh = delete PRD
# ============================================================

# AC4-happy: explicit 'fresh' mode branch that handles PRD deletion
count=$(grep_count "MODE.*==.*fresh\|== 'fresh'\|==\"fresh\"" "$INIT")
assert_ge "$count" 1 "AC4-happy: explicit 'fresh' mode branch in init_ralph_desk.zsh"

# AC4-negative: PRD deletion is scoped to fresh mode (not in improve branch)
count=$(grep_count 'fresh.*prd\|prd.*fresh\|PRD.*fresh\|fresh.*PRD' "$INIT")
assert_ge "$count" 1 "AC4-negative: PRD deletion tied to fresh mode in init_ralph_desk.zsh"

# AC4-boundary: no-PRD fallback to first-run present
count=$(grep_count 'first.run\|no PRD\|PRD.*not.*found\|treating as first' "$INIT")
assert_ge "$count" 1 "AC4-boundary: no-PRD fallback to first-run in init_ralph_desk.zsh"

# ============================================================
# AC5: PRD preserved in improve mode
# ============================================================

# AC5-happy: improve mode language / Preserved note for PRD
count=$(grep_count 'Preserved.*prd\|Preserved.*PRD\|improve.*PRD\|PRD.*improve\|prd.*improve' "$INIT")
assert_ge "$count" 1 "AC5-happy: PRD preserved language in init_ralph_desk.zsh"

# AC5-negative: improve mode branch exists in script
count=$(grep_count "MODE.*==.*improve\|== 'improve'\|==\"improve\"" "$INIT")
assert_ge "$count" 1 "AC5-negative: explicit 'improve' mode branch in init_ralph_desk.zsh"

# AC5-boundary: both fresh and improve documented in usage comment or help text
count=$(grep_count 'fresh|improve\|improve.*fresh\|fresh.*improve' "$INIT")
assert_ge "$count" 1 "AC5-boundary: both fresh and improve documented in init_ralph_desk.zsh"

# ============================================================
# AC6: Verifier 5th reasoning category — Worker Process Audit
# ============================================================

# AC6-happy: Worker Process Audit present at least once (step heading + reasoning entry = 2 is correct)
count=$(grep_count 'Worker Process Audit' "$INIT")
assert_ge "$count" 1 "AC6-happy: Worker Process Audit appears >= 1 time in init_ralph_desk.zsh"

# AC6-negative: Worker Process Audit appears in JSON reasoning array (check: double-quoted)
count=$(grep_count '"Worker Process Audit"' "$INIT")
assert_ge "$count" 1 "AC6-negative: Worker Process Audit in JSON reasoning array in init_ralph_desk.zsh"

# AC6-boundary: all 5 reasoning category keys present in init script
gov1=$(grep_count 'IL-1 Evidence Gate' "$INIT")
gov2=$(grep_count 'Layer Enforcement' "$INIT")
gov3=$(grep_count 'Test Sufficiency' "$INIT")
gov4=$(grep_count 'Anti-Gaming' "$INIT")
gov5=$(grep_count 'Worker Process Audit' "$INIT")
total=$((gov1 + gov2 + gov3 + gov4 + gov5))
assert_ge "$total" 5 "AC6-boundary: all 5 reasoning categories present in init_ralph_desk.zsh"

# ============================================================
# AC7: governance.md re-execution lifecycle annotations
# ============================================================

# AC7-happy: 'versioned' annotation present in governance.md File Structure
count=$(grep_count 'versioned' "$GOV")
assert_ge "$count" 1 "AC7-happy: 'versioned' annotation in governance.md"

# AC7-negative: in-place/improve | deleted/fresh annotation for PRD
count=$(grep_count 'in-place.*improve\|improve.*in-place\|deleted.*fresh\|fresh.*deleted' "$GOV")
assert_ge "$count" 1 "AC7-negative: PRD in-place/improve vs deleted/fresh annotation in governance.md"

# AC7-boundary: 'regenerated' annotation present (for prompts / test-spec)
count=$(grep_count 'regenerated' "$GOV")
assert_ge "$count" 1 "AC7-boundary: 'regenerated' annotation in governance.md"

# ============================================================
# AC8: Brainstorm → init mode transport (rlp-desk.md)
# ============================================================

# AC8-happy: --mode improve passed from brainstorm in rlp-desk.md
count=$(grep_count '\-\-mode improve' "$CMD")
assert_ge "$count" 1 "AC8-happy: --mode improve in rlp-desk.md brainstorm section"

# AC8-negative: --mode fresh passed from brainstorm in rlp-desk.md
count=$(grep_count '\-\-mode fresh' "$CMD")
assert_ge "$count" 1 "AC8-negative: --mode fresh in rlp-desk.md brainstorm section"

# AC8-boundary: init invocation in rlp-desk.md shows [--mode ...] optional argument
count=$(grep_count '\[--mode' "$CMD")
assert_ge "$count" 1 "AC8-boundary: init invocation shows [--mode] optional arg in rlp-desk.md"

# ============================================================
# AC9: Init summary output for re-execution
# ============================================================

# AC9-happy: versioned output keyword present in init script
count=$(grep_count '[Vv]ersioned\|Versioned:' "$INIT")
assert_ge "$count" 1 "AC9-happy: versioned output in init_ralph_desk.zsh"

# AC9-negative: deleted/removed output present in init script
count=$(grep_count 'Deleted\|deleted.*artifact\|artifacts' "$INIT")
assert_ge "$count" 1 "AC9-negative: deleted output in init_ralph_desk.zsh"

# AC9-boundary: re-execution summary label printed
count=$(grep_count 'Re-execution.*summary\|re-execution.*summary\|Re-execution mode\|summary:' "$INIT")
assert_ge "$count" 1 "AC9-boundary: re-execution summary output in init_ralph_desk.zsh"

# ============================================================
# AC10: Backward compatibility — no --mode = first-run behavior
# ============================================================

# AC10-happy: zsh syntax check passes
if zsh -n "$INIT" 2>/dev/null; then
  pass "AC10-happy: init_ralph_desk.zsh passes zsh -n syntax check"
else
  fail "AC10-happy: init_ralph_desk.zsh fails zsh -n syntax check"
fi

# AC10-negative: MODE defaults to empty string (no --mode = no mode logic triggered)
count=$(grep_count 'MODE=""' "$INIT")
assert_ge "$count" 1 "AC10-negative: MODE defaults to empty string in init_ralph_desk.zsh"

# AC10-boundary: mode lifecycle logic only runs when MODE is non-empty AND PRD exists
count=$(grep_count '\[\[ -n.*MODE.*\]\]\|\[\[ -n "\$MODE" \]\]' "$INIT")
assert_ge "$count" 1 "AC10-boundary: mode logic guarded by non-empty MODE condition"

# ============================================================
# AC11: version_file handles ONLY campaign-report and debug.log, NOT SV reports
# ============================================================

# AC11-happy: version_file called for debug.log
count=$(grep_count 'version_file.*debug\.log\|debug\.log.*version_file' "$INIT")
assert_ge "$count" 1 "AC11-happy: version_file called for debug.log in init_ralph_desk.zsh"

# AC11-negative: version_file called for campaign-report.md
count=$(grep_count 'version_file.*campaign-report\|campaign-report.*version_file' "$INIT")
assert_ge "$count" 1 "AC11-negative: version_file called for campaign-report.md in init_ralph_desk.zsh"

# AC11-boundary: version_file NOT called for self-verification-report
count=$(grep_count 'version_file.*self-verification\|self-verification.*version_file' "$INIT")
assert_zero "$count" "AC11-boundary: version_file NOT called for self-verification-report"

# ============================================================
# AC12: Existing project-local prompts unchanged when template updated
# ============================================================

# AC12-happy: prompts guarded by [[ ! -f "$F" ]] (at least 2: worker + verifier)
count=$(grep_count '! -f "\$F"' "$INIT")
assert_ge "$count" 2 "AC12-happy: prompts guarded by [[ ! -f \"\$F\" ]] (>= 2 guards)"

# AC12-negative: no unconditional overwrite outside re-execution block
# Verify [[ ! -f ]] guard exists before verifier prompt heredoc
count=$(grep_count '! -f "\$F"\|! -f.*\$F' "$INIT")
assert_ge "$count" 2 "AC12-negative: [[ ! -f ]] guards protect all prompt files"

# AC12-boundary: re-execution only deletes CURRENT slug's prompts (path uses $SLUG)
count=$(grep_count '\$SLUG.*worker\.prompt\|\$SLUG.*verifier\.prompt' "$INIT")
assert_ge "$count" 1 "AC12-boundary: re-execution deletes only current slug's prompts (uses \$SLUG)"

# ============================================================
# AC13: --mode with no PRD → ignore mode, treat as first run
# ============================================================

# AC13-happy: fallback to first-run language when no PRD exists
count=$(grep_count 'first.run\|treating as first\|no PRD.*found\|PRD.*not.*exist' "$INIT")
assert_ge "$count" 1 "AC13-happy: no-PRD fallback to first-run in init_ralph_desk.zsh"

# AC13-negative: MODE reset to empty when no PRD exists
count=$(grep_count 'MODE=""' "$INIT")
assert_ge "$count" 1 "AC13-negative: MODE reset when no PRD exists in init_ralph_desk.zsh"

# AC13-boundary: note printed when --mode provided but no PRD (non-silent)
count=$(grep_count 'Note.*mode\|note.*--mode\|--mode.*no PRD\|no PRD.*mode\|--mode.*provided.*no PRD' "$INIT")
assert_ge "$count" 1 "AC13-boundary: note printed when --mode provided but no PRD in init_ralph_desk.zsh"

# ============================================================
# L3 Runtime E2E Tests (temp-directory execution)
# Covers the real improve/fresh/no-PRD lifecycle that grep-only
# tests cannot verify (AC2, AC3, AC4, AC5, AC9, AC13).
# ============================================================

_run_init() {
  # _run_init <slug> <objective> [extra args...]
  # Sets up minimal temp dir, runs init, returns exit code via $INIT_RC
  # Caller must unset TMPD after use
  TMPD=$(mktemp -d)
  mkdir -p "$TMPD/.claude/ralph-desk/plans" \
           "$TMPD/.claude/ralph-desk/logs/$1" \
           "$TMPD/.claude/ralph-desk/memos" \
           "$TMPD/.claude/ralph-desk/context"
  local slug="$1"; shift
  local obj="$1"; shift
  ROOT="$TMPD" zsh "$INIT" "$slug" "$obj" "$@" >"$TMPD/stdout.txt" 2>"$TMPD/stderr.txt"
  INIT_RC=$?
}

# --- improve mode (with existing PRD + debug.log) ---
echo "old-prd-content" > /tmp/_us004_prd_check_$$.tmp
SLUG_T="tslug"

# AC2-runtime-happy: --mode improve exits 0 and versions debug.log to debug-v1.log
_run_init "$SLUG_T" "obj" --mode improve
# no PRD yet → fallback path; just verify exit 0
if [[ $INIT_RC -eq 0 ]]; then
  pass "AC2-runtime-happy: --mode improve (no PRD fallback) exits 0"
else
  fail "AC2-runtime-happy: --mode improve (no PRD fallback) exits 0 (got $INIT_RC, stderr: $(cat "$TMPD/stderr.txt"))"
fi
rm -rf "$TMPD"

# AC2-runtime-negative: --mode improve with PRD+debug.log creates debug-v1.log (version_file works)
_run_init "$SLUG_T" "obj"  # first run — creates PRD + scaffold
PRD_PATH="$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md"
touch "$TMPD/.claude/ralph-desk/logs/$SLUG_T/debug.log"
ROOT="$TMPD" zsh "$INIT" "$SLUG_T" "obj" --mode improve >"$TMPD/stdout2.txt" 2>"$TMPD/stderr2.txt"
RC2=$?
if [[ $RC2 -eq 0 ]] && [[ -f "$TMPD/.claude/ralph-desk/logs/$SLUG_T/debug-v1.log" ]]; then
  pass "AC2-runtime-negative: --mode improve creates debug-v1.log (version_file functional)"
else
  fail "AC2-runtime-negative: --mode improve creates debug-v1.log (exit=$RC2, stderr: $(cat "$TMPD/stderr2.txt"))"
fi
rm -rf "$TMPD"

# AC2-runtime-boundary: --mode fresh with PRD+debug.log creates debug-v1.log
_run_init "$SLUG_T" "obj"  # first run — creates PRD
touch "$TMPD/.claude/ralph-desk/logs/$SLUG_T/debug.log"
ROOT="$TMPD" zsh "$INIT" "$SLUG_T" "obj" --mode fresh >"$TMPD/stdout3.txt" 2>"$TMPD/stderr3.txt"
RC3=$?
if [[ $RC3 -eq 0 ]] && [[ -f "$TMPD/.claude/ralph-desk/logs/$SLUG_T/debug-v1.log" ]]; then
  pass "AC2-runtime-boundary: --mode fresh exits 0 and creates debug-v1.log"
else
  fail "AC2-runtime-boundary: --mode fresh exits 0 and creates debug-v1.log (exit=$RC3, stderr: $(cat "$TMPD/stderr3.txt"))"
fi
rm -rf "$TMPD"

# AC4-runtime-happy: --mode fresh deletes old PRD content (fresh PRD created from template)
_run_init "$SLUG_T" "obj"  # create initial PRD
echo "old-unique-prd-marker-abc123" > "$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md"
ROOT="$TMPD" zsh "$INIT" "$SLUG_T" "obj" --mode fresh >/dev/null 2>&1
RC4=$?
PRESERVED=$(grep -c 'old-unique-prd-marker-abc123' "$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md" 2>/dev/null) || PRESERVED=0
if [[ $RC4 -eq 0 ]] && [[ $PRESERVED -eq 0 ]]; then
  pass "AC4-runtime-happy: --mode fresh exits 0 and removes old PRD content"
else
  fail "AC4-runtime-happy: --mode fresh exits 0 and removes old PRD content (exit=$RC4, old_marker_count=$PRESERVED)"
fi
rm -rf "$TMPD"

# AC5-runtime-happy: --mode improve preserves PRD content unchanged
_run_init "$SLUG_T" "obj"  # create initial PRD
echo "preserve-this-prd-content-xyz" > "$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md"
ROOT="$TMPD" zsh "$INIT" "$SLUG_T" "obj" --mode improve >/dev/null 2>&1
RC5=$?
PRESERVED2=$(grep -c 'preserve-this-prd-content-xyz' "$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md" 2>/dev/null) || PRESERVED2=0
if [[ $RC5 -eq 0 ]] && [[ $PRESERVED2 -ge 1 ]]; then
  pass "AC5-runtime-happy: --mode improve exits 0 and preserves PRD content"
else
  fail "AC5-runtime-happy: --mode improve exits 0 and preserves PRD content (exit=$RC5, preserved_count=$PRESERVED2)"
fi
rm -rf "$TMPD"

# AC9-runtime-happy: --mode improve outputs Re-execution summary label
_run_init "$SLUG_T" "obj"  # create PRD
ROOT="$TMPD" zsh "$INIT" "$SLUG_T" "obj" --mode improve >"$TMPD/out_ac9.txt" 2>&1
RC9=$?
SUMMARY_LINE=$(grep -c 'Re-execution summary\|Re-execution mode' "$TMPD/out_ac9.txt" 2>/dev/null) || SUMMARY_LINE=0
if [[ $RC9 -eq 0 ]] && [[ $SUMMARY_LINE -ge 1 ]]; then
  pass "AC9-runtime-happy: --mode improve outputs re-execution summary label"
else
  fail "AC9-runtime-happy: --mode improve outputs re-execution summary label (exit=$RC9, count=$SUMMARY_LINE)"
fi
rm -rf "$TMPD"

# AC13-runtime-happy: --mode improve with no PRD exits 0 and creates PRD from template
_run_init "$SLUG_T" "obj" --mode improve  # no PRD exists
RC13=$?
NOTE_LINE=$(grep -c 'treating as first\|no PRD' "$TMPD/stdout.txt" 2>/dev/null) || NOTE_LINE=0
PRD_CREATED=$([ -f "$TMPD/.claude/ralph-desk/plans/prd-$SLUG_T.md" ] && echo 1 || echo 0)
if [[ $RC13 -eq 0 ]] && [[ $NOTE_LINE -ge 1 ]] && [[ $PRD_CREATED -eq 1 ]]; then
  pass "AC13-runtime-happy: --mode with no PRD exits 0, prints note, creates fresh PRD"
else
  fail "AC13-runtime-happy: --mode with no PRD exits 0, prints note, creates fresh PRD (exit=$RC13, note=$NOTE_LINE, prd=$PRD_CREATED)"
fi
rm -rf "$TMPD"
rm -f /tmp/_us004_prd_check_$$.tmp

# ============================================================
# Summary
# ============================================================
echo ""
echo "==================================================="
echo "US-004 Results: PASS=$PASS  FAIL=$FAIL  TOTAL=$((PASS+FAIL))"
if [[ $FAIL -eq 0 ]]; then
  echo "STATUS: ALL PASS"
  exit 0
else
  echo "STATUS: $FAIL FAILURE(S)"
  exit 1
fi
