import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { readStatus } from '../../src/node/reporting/campaign-reporting.mjs';

// IMP-04 — status.json schema parity (zsh producer ↔ Node reader).
//
// The production zsh leader's update_status (lib_ralph_desk.zsh) writes
// `max_iter` and NO `final_verifier_model`; readStatus historically read
// `max_iterations ?? 100` and `final_verifier_model ?? 'unknown'` — the
// CLI-unreachable Node leader's schema. Result on every production campaign:
// a wrong denominator ("Iteration: 3 / 100" for a --max-iter 42 run) and a
// bogus "unknown (final)".
//
// Contract pinned here: the fixture is generated by the REAL zsh producer
// (source lib, set leader globals, call update_status) — NOT a hand-built
// JSON — so any future writer-schema drift re-breaks this test.

const testFile = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(testFile), '..', '..');
const LIB = path.join(repoRoot, 'src', 'scripts', 'lib_ralph_desk.zsh');

async function createTempDir(t) {
  const tempRoot = path.join(repoRoot, '.tmp', 'imp04-status-parity');
  await fs.mkdir(tempRoot, { recursive: true });
  const directory = await fs.mkdtemp(path.join(tempRoot, 'case-'));
  t.after(async () => {
    await fs.rm(directory, { recursive: true, force: true });
  });
  return directory;
}

// Run the REAL zsh update_status with the leader globals it dereferences.
function produceStatusWithZsh(statusFile) {
  const script = `
    source ${JSON.stringify(LIB)} 2>/dev/null
    log(){ :; }; log_error(){ :; }; log_debug(){ :; }
    SLUG=imp04-fixture
    BASELINE_COMMIT=abc1234
    ITERATION=3
    MAX_ITER=42
    WORKER_MODEL=haiku
    VERIFIER_MODEL=haiku
    WORKER_ENGINE=claude
    VERIFIER_ENGINE=claude
    WORKER_CODEX_MODEL=""
    WORKER_CODEX_REASONING=""
    VERIFIER_CODEX_MODEL=""
    VERIFIER_CODEX_REASONING=""
    VERIFY_MODE=per-us
    CONSENSUS_MODE=off
    CONSECUTIVE_FAILURES=0
    VERIFIED_US=""
    STATUS_FILE=${JSON.stringify(statusFile)}
    update_status worker ok
  `;
  return spawnSync('zsh', ['--no-rcs', '-c', script], { encoding: 'utf8' });
}

test('IMP-04: readStatus renders the zsh writer schema (max_iter, no final_verifier_model)', async (t) => {
  const rootDir = await createTempDir(t);
  const slug = 'imp04-fixture';
  const runtimeDir = path.join(rootDir, '.rlp-desk', 'logs', slug, 'runtime');
  await fs.mkdir(runtimeDir, { recursive: true });
  const statusFile = path.join(runtimeDir, 'status.json');

  const zsh = produceStatusWithZsh(statusFile);
  assert.equal(zsh.status, 0, `zsh update_status failed: ${zsh.stderr}`);
  const produced = JSON.parse(await fs.readFile(statusFile, 'utf8'));
  // Guard the premise: the real writer emits max_iter and omits the
  // Node-leader-only keys. If the writer ever changes, this test must be
  // revisited alongside the reader.
  assert.equal(produced.max_iter, 42);
  assert.equal('max_iterations' in produced, false);
  assert.equal('final_verifier_model' in produced, false);

  const out = await readStatus(slug, { rootDir });

  assert.match(out, /Iteration: 3 \/ 42/, `wrong denominator:\n${out}`);
  assert.doesNotMatch(out, /\/ 100\b/, `fell back to the /100 default:\n${out}`);
  assert.doesNotMatch(out, /unknown \(final\)/, `bogus final-verifier render:\n${out}`);
});

test('IMP-04: readStatus still honors the Node-leader schema (max_iterations, final_verifier_model)', async (t) => {
  const rootDir = await createTempDir(t);
  const slug = 'imp04-node-schema';
  const runtimeDir = path.join(rootDir, '.rlp-desk', 'logs', slug, 'runtime');
  await fs.mkdir(runtimeDir, { recursive: true });
  await fs.writeFile(
    path.join(runtimeDir, 'status.json'),
    JSON.stringify({
      slug,
      iteration: 5,
      max_iterations: 20,
      phase: 'verify',
      worker_model: 'haiku',
      verifier_model: 'haiku',
      final_verifier_model: 'opus',
      verified_us: [],
      consecutive_failures: 0,
      updated_at_utc: '2026-07-07T00:00:00Z',
    }),
  );

  const out = await readStatus(slug, { rootDir });

  assert.match(out, /Iteration: 5 \/ 20/);
  assert.match(out, /opus \(final\)/);
});
